config/routes.rb
Rails.application.routes.draw do
  resources :borrows
  resources :transactions
  get 'sessions/new'
  get '/friends/:id', to: 'users#show_friends', as: 'friends'
  post '/friends/:id', to: 'users#add_friends', as: 'add_friends'
  get 'admin/:id', to: 'admin#show', as: 'admin'
  get '/admin/new', to: 'admin#new', as: 'new_admin'
  post '/admin', to: 'admin#create', as: 'admins'
  get '/view_admins', to:'admin#view_admins', as: 'view_admins'
  get '/view_users', to:'admin#view_users', as:'view_users'
  resources :accounts
  resources :users
  get '/contact', to: 'static_pages#contact'
  get  '/signup',  to: 'users#new'
  post '/signup',  to: 'users#create'
  get '/show_accounts', to: 'admin#show_accounts', as: 'show_accounts'
  post '/act_account/:id', to: 'admin#state_change_account', as:'change_state_account'
  root 'sessions#new'
  get '/view_trans/:id', to:'accounts#view_trans', as: 'view_trans'
  get '/showtrans/:id', to: 'users#show_trans', as: 'show_trans'
  get '/show_pending_t', to: 'admin#show_ptrans', as: 'show_ptrans'
  post '/manage_trans/:id', to: 'admin#manage_transaction', as: 'manage_trans'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout', to: 'sessions#log_out'
  get '/index_user', to: 'transactions#index_user', as: 'user_trans'
  get '/accept_offer', to: 'borrows#accept_offer', as: 'accept_offer'
  get '/reject_offer', to: 'borrows#reject_offer', as: 'reject_offer'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/admin/_user.html.erb
<div>
  <% if !user.admin? %>
      <li>
        <%= link_to user.name, user %>
        <% if current_user.admin? && !current_user?(user) %>
      |   <%= link_to "delete", user, method: :delete,
                    data: {confirm: "You sure?"} %>
        <% end %>

      </li>
  <% end %>
</div>

app/views/admin/edit.html.erb
<% provide(:title, "Edit user") %>
<h1>Update profile</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@user) do |f| %>
        <%= render 'shared/error_messages' %>

        <%= f.label :name %>
        <%= f.text_field :name, class: 'form-control' %>

        <%= f.label :email %>
        <%= f.email_field :email, class: 'form-control' %>

        <%= f.label :password %>
        <%= f.password_field :password, class: 'form-control' %>

        <%= f.label :password_confirmation, "Confirmation" %>
        <%= f.password_field :password_confirmation, class: 'form-control' %>

        <%= f.submit "Save changes", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/admin/index.html.erb
<% provide(:title, 'All users') %>
<h1>All users</h1>

<ul class="users">
  <%= render @users %>
</ul>

<%= link_to 'New User', new_user_path %>

app/views/admin/show.html.erb
<%= javascript_include_tag "application" %>

<div class="col-sm-6">
  <div class="jumbotron">

    <p>
      <strong>Name:</strong>
      <%= @user.name %>
    </p>

    <p>
      <strong>Email:</strong>
      <%= @user.email %>
    </p>

    <p>
      <strong>Phone:</strong>
      <%= @user.phone %>
    </p>
  </div>
</div>

<div class="col-sm-4">
  <br><br>
  <%= button_to "Show All Accounts", show_accounts_path, method: :get, class: "btn btn-primary custom3" %>
  <br>
  <%= button_to "Show Pending Transactions", show_ptrans_path, method: :get, class: "btn btn-primary custom3" %>
  <br>
  <%= button_to "Create Admin/User", signup_path, method: :get, class: "btn btn-primary custom3" %>
  <br>
  <%= button_to "View all Admins", view_admins_path, method: :get, class: "btn btn-primary custom3" %>
  <br>
  <%= button_to "View all Users", view_users_path, method: :get, class: "btn btn-primary custom3" %>
</div>

app/views/admin/show_accounts.html.erb
<%if @pending_accounts %>
<h1>Pending Accounts</h1>

<table class="table table-striped">
  <thead>
  <tr>
    <th>Account</th>
    <th>User</th>
    <th>Balance</th>
    <th colspan="3"></th>
  </tr>
  </thead>

  <tbody>
  <% @pending_accounts.each do |account| %>
      <tr>
        <td><%= account.acc_no %></td>
        <td><%= account.user_id %></td>
        <td><%= account.balance %></td>
        <td><%= button_to 'Activate', change_state_account_path(id: account.id, chg_state: :active), method: :post, class: "btn btn-primary" %></td>
        <td><%= button_to 'Destroy', account, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger" %></td>
      </tr>
  <% end %>
  </tbody>
</table>
<% end %>


<h1>Activated Accounts</h1>
<table class="table table-striped">
  <thead>
  <tr>
    <th>Account</th>
    <th>User</th>
    <th>Balance</th>
    <th colspan="3"></th>
  </tr>
  </thead>

  <tbody>
  <% @activated_accounts.each do |account| %>
      <tr>
        <td><%= account.acc_no %></td>
        <td><%= account.user_id %></td>
        <td><%= account.balance %></td>
        <td><%= button_to 'Deactivate', change_state_account_path(id: account.id, chg_state: :inactive) , method: :post, class: "btn btn-warning" %></td>
        <td><%= button_to 'Destroy', account, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger" %></td>
        <td><%#= button_to 'Transaction History', view_trans_path(id: account.id) , method: :get, class: "btn btn-primary" %></td>
      </tr>
  <% end %>
  </tbody>
</table>
<div>
<% link_to 'Back', admin_path(current_user[:id]), method: :get, class: "btn btn-primary" %>
</div>

app/views/admin/show_ptrans.html.erb
<%if @pending_trans %>
    <h1>Pending Transactions</h1>

    <table class="table table-striped">
      <thead>
      <tr>
        <th>From</th>
        <th>To</th>
        <th>Type</th>
        <th>Amount</th>
        <th colspan="4"></th>
      </tr>
      </thead>

      <tbody>
      <% @pending_trans.each do |trans| %>
          <tr>
            <td><%=  trans.from %></td>
            <td><%=  trans.to %></td>
            <td><%=  trans.amount %></td>
            <td><%=  trans.kind.capitalize%></td>
            <td><%= button_to 'Approve', manage_trans_path(id: trans.id, chg_state: :accepted), method: :post, class: "btn btn-primary" %></td>
            <td><%= button_to 'Reject', manage_trans_path(id: trans.id, chg_state: :rejected), method: :post, data: { confirm: 'Are you sure?' }, class: "btn btn-danger" %></td>
          </tr>
      <% end %>
      </tbody>
    </table>
<% else %>
    <br>
    <h1>No Pending Transactions</h1>
<% end %>

<%= button_to 'Back', admin_path(current_user[:id]), method: :get, class: "btn btn-primary col1" %>

app/views/admin/view_admins.html.erb
<h1>Admins</h1>

<table class="table table-striped">
  <thead>
  <tr>
    <th>Name</th>
    <th>Email</th>
    <th>Phone</th>
    <th colspan="3"></th>
  </tr>
  </thead>

  <tbody>
  <% @admins.each do |admin| %>
      <tr>
        <td><%=  admin.name %></td>
        <td><%=  admin.email %></td>
        <td><%=  admin.phone %></td>
        <% if admin.email != "super@admin.com" %>
            <td><%= button_to 'Destroy', admin, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger custom2 active"%></td>
        <%else %>
            <td><%= button_to 'Destroy', admin, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger custom2 disabled"%></td>
      <% end %>
      </tr>
  <% end %>
  </tbody>
</table>

<%= button_to 'Back', admin_path(current_user[:id]), method: :get, class: "btn btn-primary col1" %>

app/views/admin/view_users.html.erb
<h1>Users</h1>

<table class="table table-striped">
  <thead>
  <tr>
    <th>Name</th>
    <th>Email</th>
    <th>Phone</th>
    <th colspan="3"></th>
  </tr>
  </thead>

  <tbody>
  <% @users.each do |user| %>
      <tr>
        <td><%=  user.name %></td>
        <td><%=  user.email %></td>
        <td><%=  user.phone %></td>
        <td><%= button_to 'Accounts', account_path(:id => user.id), method: :get, class:"btn btn-primary custom2"%></td>
        <td><%= link_to 'Transactions',user_trans_path(:user_id => user.id), class:"btn btn-primary custom2"%></td>
        <td><%= button_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger custom2"%></td>
      </tr>
  <% end %>
  </tbody>
</table>

<%= button_to 'Back', admin_path(current_user[:id]), method: :get, class: "btn btn-primary col1" %>