config/routes.rb
Rails.application.routes.draw do
  resources :borrows
  resources :transactions
  get 'sessions/new'
  get '/friends/:id', to: 'users#show_friends', as: 'friends'
  post '/friends/:id', to: 'users#add_friends', as: 'add_friends'
  get 'admin/:id', to: 'admin#show', as: 'admin'
  get '/admin/new', to: 'admin#new', as: 'new_admin'
  post '/admin', to: 'admin#create', as: 'admins'
  get '/view_admins', to:'admin#view_admins', as: 'view_admins'
  get '/view_users', to:'admin#view_users', as:'view_users'
  resources :accounts
  resources :users
  get '/contact', to: 'static_pages#contact'
  get  '/signup',  to: 'users#new'
  post '/signup',  to: 'users#create'
  get '/show_accounts', to: 'admin#show_accounts', as: 'show_accounts'
  post '/act_account/:id', to: 'admin#state_change_account', as:'change_state_account'
  root 'sessions#new'
  get '/view_trans/:id', to:'accounts#view_trans', as: 'view_trans'
  get '/showtrans/:id', to: 'users#show_trans', as: 'show_trans'
  get '/show_pending_t', to: 'admin#show_ptrans', as: 'show_ptrans'
  post '/manage_trans/:id', to: 'admin#manage_transaction', as: 'manage_trans'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout', to: 'sessions#log_out'
  get '/index_user', to: 'transactions#index_user', as: 'user_trans'
  get '/accept_offer', to: 'borrows#accept_offer', as: 'accept_offer'
  get '/reject_offer', to: 'borrows#reject_offer', as: 'reject_offer'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
  before_save { self.email = email.downcase }
  validates :name , presence: true , length: {maximum: 50}
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i
  validates :email , presence: true, length: { maximum:255 }, format: { with: VALID_EMAIL_REGEX }, uniqueness: {case_sensitive: false}
  has_secure_password
  validates :phone, presence: true, length: {minimum: 10, maximum: 10}
  validates :password, presence: true, length: { minimum: 4 }
  has_many  :accounts
  has_many  :friends

  def self.search(search)
    if search
      where('name LIKE ? and id != ? AND is_admin = ?', "%#{search}%", current_user[:id], false)
    else
      where('id != ? AND is_admin = ?', current_user[:id], false)
    end
  end
#
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :logged_in_user
  before_action :set_user, only: [:edit, :update, :destroy]
  before_action :logged_in_user, only: [:show, :index, :edit, :update]
  before_action :correct_user, only: [:show, :edit, :update]
  # GET /users
  # GET /users.json

  def index
    if logged_in?
      if params[:search].present?
        @users = User.where('(name LIKE ? OR email LIKE ?) and id != ? AND is_admin = ?', params[:search].strip, params[:search].strip, current_user[:id], false)
      else
        @users = User.where('id != ? AND is_admin = ?', current_user[:id], false)
      end
    else
      redirect_back login_path
    end
  end

=begin

  def index
    if logged_in? and params[:search]
      @users = User.where('name LIKE ?', params[:search]).where("id != ? AND is_admin = ?", current_user[:id], false)
      puts("In 1st method")
    else
      if logged_in?
        @users = User.where("id != ? AND is_admin = ?", current_user[:id], false)
        puts("In 1st method")
      else
        puts("In 1st method")
        redirect_to login_path
      end
    end
  end
=end

  # GET /users/1
  # GET /users/1.json
  def show
    @user = User.find(current_user[:id])
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /friends/1
  def show_friends
    if logged_in?
      @friends = Friend.where(user_id: current_user[:id])
    else
      flash[:notice] = "Please Login"
      redirect_to login_path
    end
  end


  def show_trans
    if logged_in?
      @transactions = Transaction.where(user_id: params[:id])
    else
      redirect_to login_path
    end
  end


  def add_friends
    if logged_in?
      if Friend.exists?(user_id: current_user[:id], friend_id: params[:id], fname: params[:name])
        flash[:notice] = "Friend already in your list"
        redirect_to friends_path(current_user)
      else
        f = Friend.new(user_id: current_user[:id], friend_id: params[:id], fname: params[:name])
        if f.save
          flash[:notice] = "New Friend Added"
          redirect_to friends_path(current_user)
        end
      end
    end
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)
    if @user.save
      if logged_in? and current_user[:is_admin]
        redirect_to admin_path(current_user[:id])
      else
        log_in @user
        redirect_to @user
      end
    else
      render 'new'
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        if is_admin?
          format.html { redirect_to admin_path(current_user[:id]), notice: 'User was successfully updated.' }
        else
          format.html { redirect_to @user, notice: 'User was successfully updated.' }
          format.json { render :show, status: :ok, location: @user }
        end
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    a = Account.where(user_id: params[:id])
    a.delete_all
    t = Transaction.where(:user_id => params[:id])
    t.delete_all
    b = Borrow.where(["user_id = ? or friend_id = ?", params[:id], params[:id]])
    b.delete_all
    f = Friend.where(:friend_id => params[:id])
    f.delete_all
    User.find(params[:id]).destroy
    redirect_to admin_path(current_user[:id])
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def logged_in_user
    unless logged_in?
      flash[:danger] = "Please log in."
      redirect_to login_path
    end
  end


  # Confirms the correct user.
  def correct_user
    @user = User.find(current_user[:id])
    redirect_to(login_path) unless current_user?(@user)
  end

  def set_user
    @user = User.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def user_params
    params.require(:user).permit(:name, :email, :password, :phone, :is_admin)
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(user) do |f| %>
        <% if user.errors.any? %>
            <div id="error_explanation">
              <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

              <ul>
                <% user.errors.full_messages.each do |message| %>
                    <li><%= message %></li>
                <% end %>
              </ul>
            </div>
        <% end %>
        <div>
          <div class="field">
            <%= f.label :name %>
            <%= f.text_field :name, class: 'form-control' %>
          </div>

          <div class="field">
            <%= f.label :email %>
            <%= f.email_field :email, class: 'form-control' %>
          </div>

          <div class="field">
            <%= f.label :password %>
            <%= f.password_field :password, class: 'form-control' %>
          </div>

          <div class="field">
            <%= f.label :phone %>
            <%= f.number_field :phone, class: 'form-control' %>
          </div>
          <% if logged_in? and current_user[:is_admin] == true %>
          <div>
            <%= f.label :is_admin %>
            <%= f.check_box :is_admin, {}, true, false %>
          </div>
          <% end %>
          <div class="actions">
            <%= f.submit class: "btn btn-primary" %>
          </div>
        </div>
    <% end %>
  </div>
</div>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>

<% if is_admin? %>
  <%= link_to 'Back', admin_path(current_user[:id]) %>
<% else %>
  <%= link_to 'Back', @user %>
<% end %>

app/views/users/index.html.erb
<% provide(:title, 'All users') %>
<h1>Add Friends</h1>
<div>
  <table>
    <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th>Phone</th>
      <th colspan="3"></th>
    </tr>
    </thead>

    <tbody>
    <% @users.each do |user| %>
        <tr>
          <td><%= user.name %></td>
          <td><%= user.email %></td>
          <td><%= user.phone %></td>
          <td><%= button_to 'Add', add_friends_path(:id => user.id, :name => user.name), method: :post, class: "btn btn-primary custom2" %></td>
        </tr>
    <% end %>
    </tbody>
  </table>
</div>


<div>
  <%= form_tag(users_path, method: :get) do %>
      <div>
        <%= text_field_tag :search, params[:search], placeholder: 'Search user by name or email'%>
      </div>
      <div>
        <%= submit_tag 'Search', name: nil, class: 'btn btn-primary custom2' %>
      </div>
  <% end %>
</div>

app/views/users/new.html.erb
<h1>New User Registration</h1>

<%= render 'form', user: @user %>

app/views/users/show.html.erb
<%= javascript_include_tag "application" %>

<div class="col-sm-6">
<div class="jumbotron">
  <p>
    <strong>Name:</strong>
    <%= @user.name %>
  </p>

  <p>
    <strong>Email:</strong>
    <%= @user.email %>
  </p>

  <p>
    <strong>Phone:</strong>
    <%= @user.phone %>
  </p>
</div>
</div>

<div class="col-sm-4">
  <br><br>
<div class="btn-group">
  <%= button_to 'Request for an account', new_account_url, method: :get, class: "btn btn-primary custom3" %>
  <br>
  <%= button_to 'View your accounts', account_path, method: :get, class: "btn btn-primary custom3" %>
  <br>
  <%= button_to 'View your Friends', friends_path(@user), method: :get, class: "btn btn btn-info custom3"%>
  <br>
  <%= link_to 'View your borrow requests', borrows_path(:user_id => @user.id), method: :get, class: "btn btn btn-info custom3"%>
</div>
</div>

app/views/users/show_friends.html.erb
<h2>My Friends</h2>

<table class="table table-striped" >
  <thead>
  <tr>
    <th>Name</th>
  </tr>
  </thead>

  <tbody>
  <% if @friends %>
    <% @friends.each do |friend| %>
        <tr>
          <td><%= friend.fname.capitalize %></td>
          <td><%= link_to 'Borrow request', new_borrow_path(:user_id => friend.user_id, :friend_id => friend.friend_id ) %></td>
        </tr>
    <% end %>
  <% end %>
  </tbody>
</table>

<br>
<p>
  <%= button_to 'Add Friends', users_path, method: :get, class: "btn btn-primary custom3" %>
</p>

app/views/users/show_trans.html.erb
<h2>My Transactions</h2>

<table class="table table-striped">
  <thead>
  <tr>
    <th class="col1">From</th>
    <th class="col1">To</th>
    <th class="col1">Amount</th>
    <th class="col1">Type</th>
    <th class="col1">Status</th>
  </tr>
  </thead>

  <tbody>
  <% if @transactions %>
      <% @transactions.each do |transaction| %>
          <tr>
            <td><%= transaction.from %></td>
            <td><%= transaction.to %></td>
            <td><%= transaction.amount%></td>
            <td><%= transaction.kind.capitalize%></td>
            <td><%= transaction.state.capitalize%></td>
          </tr>
      <% end %>
  <% end %>
  </tbody>
</table>

<br>
<p>
  <%= link_to 'Back', user_path %>
</p>