config/routes.rb
Rails.application.routes.draw do
  resources :borrows
  resources :transactions
  get 'sessions/new'
  get '/friends/:id', to: 'users#show_friends', as: 'friends'
  post '/friends/:id', to: 'users#add_friends', as: 'add_friends'
  get 'admin/:id', to: 'admin#show', as: 'admin'
  get '/admin/new', to: 'admin#new', as: 'new_admin'
  post '/admin', to: 'admin#create', as: 'admins'
  get '/view_admins', to:'admin#view_admins', as: 'view_admins'
  get '/view_users', to:'admin#view_users', as:'view_users'
  resources :accounts
  resources :users
  get '/contact', to: 'static_pages#contact'
  get  '/signup',  to: 'users#new'
  post '/signup',  to: 'users#create'
  get '/show_accounts', to: 'admin#show_accounts', as: 'show_accounts'
  post '/act_account/:id', to: 'admin#state_change_account', as:'change_state_account'
  root 'sessions#new'
  get '/view_trans/:id', to:'accounts#view_trans', as: 'view_trans'
  get '/showtrans/:id', to: 'users#show_trans', as: 'show_trans'
  get '/show_pending_t', to: 'admin#show_ptrans', as: 'show_ptrans'
  post '/manage_trans/:id', to: 'admin#manage_transaction', as: 'manage_trans'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout', to: 'sessions#log_out'
  get '/index_user', to: 'transactions#index_user', as: 'user_trans'
  get '/accept_offer', to: 'borrows#accept_offer', as: 'accept_offer'
  get '/reject_offer', to: 'borrows#reject_offer', as: 'reject_offer'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/borrow.rb
class Borrow < ApplicationRecord
  enum state: [:pending, :rejected, :accepted]
  belongs_to :user
  #belongs_to :account
end

app/controllers/borrows_controller.rb
class BorrowsController < ApplicationController
  before_action :set_borrow, only: [:show, :edit, :update, :destroy]

  # GET /borrows
  # GET /borrows.json
  def index
    @borrows = Borrow.where(:friend_id => params[:user_id])
  end

  # GET /borrows/1
  # GET /borrows/1.json
  def show
  end

  # GET /borrows/new
  def new
    @borrow = Borrow.new
    @borrow.user_id = params[:user_id]
    @borrow.friend_id = params[:friend_id]
    if Account.where(:user_id => params[:friend_id]).empty?
      redirect_to borrows_path(:user_id => current_user[:id]),  notice: 'That person has no accounts'
    end
    @borrow.state ='pending'
    @borrow.friend_name = User.find_by(:id => @borrow.friend_id).name
    @borrow.user_name = User.find_by(:id => @borrow.user_id).name
    @list = Account.where(:user_id => @borrow.friend_id, :state => 'active' )
    @list2 = Account.where(:user_id => @borrow.user_id, :state => 'active')
  end

  def accept_offer
    @borrow = Borrow.find_by(:id => params[:borrow_id])
    @account1=Account.find_by(:acc_no => @borrow.from_acc)
    @account2=Account.find_by(:acc_no => @borrow.to_acc)
    @temp=@account2.balance-@borrow.amount
    if @temp < 0
      @temp = -1 * @temp
      redirect_to borrows_path(:user_id => current_user[:id]),  notice: 'Cannot lend because of insufficient funds. You are $'+@temp.to_s+' short'
      return
    end
    @account2.update_attribute(:balance,@temp)
    @temp=@account1.balance+@borrow.amount
    @account1.update_attribute(:balance,@temp)
    @borrow.update_attribute(:state, 'accepted')
    BorrowMailer.borrow_confirmation(@borrow).deliver
  end

  def reject_offer
    @borrow = Borrow.find_by(:id => params[:borrow_id])
    @borrow.update_attribute(:state, 'rejected')
    BorrowMailer.borrow_confirmation(@borrow).deliver
  end


  # GET /borrows/1/edit
  def edit
  end

  # POST /borrows
  # POST /borrows.json
  def create
    @borrow = Borrow.new(borrow_params)

    respond_to do |format|
      if @borrow.save
        format.html { redirect_to @borrow, notice: 'Borrow was successfully created.' }
        format.json { render :show, status: :created, location: @borrow }
      else
        format.html { render :new }
        format.json { render json: @borrow.errors, status: :unprocessable_entity }
      end
    end
    BorrowMailer.borrow_confirmation(@borrow).deliver
  end

  # PATCH/PUT /borrows/1
  # PATCH/PUT /borrows/1.json
  def update
    respond_to do |format|
      if @borrow.update(borrow_params)
        format.html { redirect_to @borrow, notice: 'Borrow was successfully updated.' }
        format.json { render :show, status: :ok, location: @borrow }
      else
        format.html { render :edit }
        format.json { render json: @borrow.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /borrows/1
  # DELETE /borrows/1.json
  def destroy
    @borrow.destroy
    respond_to do |format|
      format.html { redirect_to borrows_url, notice: 'Borrow was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_borrow
      @borrow = Borrow.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def borrow_params
      params.require(:borrow).permit(:user_id, :friend_id, :friend_name, :amount, :state, :from_acc, :to_acc, :user_name)
    end
end

app/helpers/borrows_helper.rb
module BorrowsHelper
end

app/views/borrows/_form.html.erb
<%= form_for(borrow) do |f| %>
  <% if borrow.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(borrow.errors.count, "error") %> prohibited this borrow from being saved:</h2>

      <ul>
      <% borrow.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

    <%= f.hidden_field :user_id, :value => @borrow.user_id %>

    <%= f.hidden_field :friend_id, :value => @borrow.friend_id %>

  <div class="field">
    <%= f.label :friend_name %>
    <%= f.text_field :friend_name, :value => @borrow.friend_name,:readonly => true  %>
  </div>

    <div class="field">
      <%= f.label :from_acc %>
      <%= f.select :from_acc, options_from_collection_for_select(@list2,:acc_no,:acc_no) %>
      <%#= f.collection_select (:to,@list,:acc_no,:acc_no) %>
    </div>

    <div class="field">
      <%= f.label :to_acc %>
      <%= f.select :to_acc, options_from_collection_for_select(@list,:acc_no,:acc_no) %>
      <%#= f.collection_select (:to,@list,:acc_no,:acc_no) %>
    </div>

  <div class="field">
    <%= f.label :amount %>
    <%= f.text_field :amount %>
  </div>

    <%= f.hidden_field :state, :value => @borrow.state %>
    <%= f.hidden_field :user_name, :value => @borrow.user_name %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/borrows/accept_offer.html.erb
<p id="notice"><%= notice %></p>


<h1>Borrow request accepted</h1>

<p>
  <strong>Friend name:</strong>
  <%= @borrow.user_name %>
</p>

<p>
  <strong>Friend account:</strong>
  <%= @borrow.from_acc %>
</p>

<p>
  <strong>Your account:</strong>
  <%= @borrow.to_acc %>
</p>

<p>
  <strong>Amount:</strong>
  <%= @borrow.amount %>
</p>

<p>
  <strong>State:</strong>
  <%= @borrow.state.capitalize %>
</p>

|
<%= link_to 'Back', borrows_path(:user_id => current_user[:id]) %>

app/views/borrows/edit.html.erb
<h1>Editing Borrow</h1>

<%= render 'form', borrow: @borrow %>

<%= link_to 'Show', @borrow %> |
<%= link_to 'Back', borrows_path %>

app/views/borrows/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Borrows</h1>

<table class="table table-striped">
  <thead>
    <tr>
      <th>Friend name</th>
      <th>Their account number</th>
      <th>Your account number</th>
      <th>Amount</th>
      <th>State</th>
      <th colspan="0"></th>
    </tr>
  </thead>

  <tbody>
    <% @borrows.each do |borrow| %>
      <tr>
        <% if borrow.state == 'pending' %>
          <td><%= borrow.user_name %></td>
          <td><%= borrow.from_acc %></td>
          <td><%= borrow.to_acc %></td>
          <td><%= borrow.amount %></td>
          <td><%= borrow.state.capitalize %></td>
          <td><%= link_to 'Accept', accept_offer_path(:borrow_id => borrow.id) %></td>
          <td><%= link_to 'Reject', reject_offer_path(:borrow_id => borrow.id) %></td>
        <%end%>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/borrows/new.html.erb
<h1>New Borrow</h1>

<%= render 'form', borrow: @borrow %>

<%= link_to 'Back', user_path(:id => current_user[:id]) %>

app/views/borrows/reject_offer.html.erb
<h1>Borrow request rejected</h1>

<%= link_to 'Back', borrows_path(:user_id => current_user[:id]) %>

app/views/borrows/show.html.erb
<p id="notice"><%= notice %></p>


<p>
  <strong>Friend name:</strong>
  <%= @borrow.friend_name %>
</p>

<p>
  <strong>Amount:</strong>
  <%= @borrow.amount %>
</p>

<p>
  <strong>Your Account:</strong>
  <%= @borrow.from_acc %>
</p>

<p>
  <strong>Friend's account:</strong>
  <%= @borrow.to_acc %>
</p>

<p>
  <strong>State:</strong>
  <%= @borrow.state.capitalize %>
</p>



|
<%= link_to 'Back', user_path(:id => current_user[:id]) %>