config/routes.rb
Rails.application.routes.draw do
  resources :borrows
  resources :transactions
  get 'sessions/new'
  get '/friends/:id', to: 'users#show_friends', as: 'friends'
  post '/friends/:id', to: 'users#add_friends', as: 'add_friends'
  get 'admin/:id', to: 'admin#show', as: 'admin'
  get '/admin/new', to: 'admin#new', as: 'new_admin'
  post '/admin', to: 'admin#create', as: 'admins'
  get '/view_admins', to:'admin#view_admins', as: 'view_admins'
  get '/view_users', to:'admin#view_users', as:'view_users'
  resources :accounts
  resources :users
  get '/contact', to: 'static_pages#contact'
  get  '/signup',  to: 'users#new'
  post '/signup',  to: 'users#create'
  get '/show_accounts', to: 'admin#show_accounts', as: 'show_accounts'
  post '/act_account/:id', to: 'admin#state_change_account', as:'change_state_account'
  root 'sessions#new'
  get '/view_trans/:id', to:'accounts#view_trans', as: 'view_trans'
  get '/showtrans/:id', to: 'users#show_trans', as: 'show_trans'
  get '/show_pending_t', to: 'admin#show_ptrans', as: 'show_ptrans'
  post '/manage_trans/:id', to: 'admin#manage_transaction', as: 'manage_trans'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout', to: 'sessions#log_out'
  get '/index_user', to: 'transactions#index_user', as: 'user_trans'
  get '/accept_offer', to: 'borrows#accept_offer', as: 'accept_offer'
  get '/reject_offer', to: 'borrows#reject_offer', as: 'reject_offer'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <% if logged_in? %>
            <% if current_user[:is_admin] %>
                <li><%= link_to "Home", admin_path(current_user[:id]) %></li>
             <% else %>
                <li><%= link_to "Home", current_user %></li>
            <% end %>
                <li><%= link_to "Edit Profile", edit_user_path(current_user) %></li>
                <li>
                  <%= link_to "Log out", logout_path, method: :delete %>
                </li>
        <% else %>
            <li><%= link_to "Log in", login_path %></li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
</script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>BankApp</title>
  <%= csrf_meta_tags %>

  <%= stylesheet_link_tag    "application", media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag "application", 'data-turbolinks-track': 'reload' %>
  <%= render 'layouts/shim' %>
</head>

<body>
<%= render 'layouts/header' %>

<div class="container">
  <% flash.each do |message_type, message| %>
      <div class="alert alert-<%= message_type %>"><%= message %></div>
  <% end %>
  <%= yield %>
  <%= render 'layouts/footer' %>
  <%= debug(params) if Rails.env.development? %>
</div>
</body>
</html>